name: migation

on:
  workflow_call:
    inputs:
      json:
        type: string
    secrets:
      CMS_MYSQL_DRIVER:
        required: true
      CMS_MYSQL_PASSWORD:
        required: true
      CMS_MYSQL_URL:
        required: true
      CMS_MYSQL_USERNAME:
        required: true
  workflow_dispatch:
    inputs:
      json:
        type: string
      CMS_MYSQL_DRIVER:
        type: string
        required: true
      CMS_MYSQL_PASSWORD:
        type: string
        required: true
      CMS_MYSQL_URL:
        type: string
        required: true
      CMS_MYSQL_USERNAME:
        type: string
        required: true
runs:
  using: 'composite'
  steps:
    - name: Commit config file
      run: |
        chmod +x mybatis-migrations-3.3.9/bin/migrate
        cd mybatis-migrations-3.3.9
        ./bin/migrate status --env=development2
        ./bin/migrate up --env=development2
        ./bin/migrate status --env=development2
