-- // create DASHBOARD_OVERVIEW_MINUTE_DATA table
CREATE TABLE `DASHBOARD_OVERVIEW_MINUTE_DATA`(
    `ID` 			VARCHAR2(25),
    `owner` 		VARCHAR2(128) NOT NULL,
    `ownerParent` VARCHAR2(128) NOT NULL,
    `records` 	NUMBER(8) NOT NULL,
    `rangeMarker` TIMESTAMP NOT NULL,
    `tag` 		VARCHAR2(10),
    `rangeStart` 	TIMESTAMP NOT NULL,
    `rangeEnd` 	TIMESTAMP NOT NULL,
    `state` 	    NUMBER(1) NOT NULL,
    `threadID` 	VARCHAR2(150) NOT NULL,
    `sign` 	    VARCHAR2(150) NOT NULL
);

-- //@UNDO
DROP TABLE `DASHBOARD_OVERVIEW_MINUTE_DATA`;
