CREATE TABLE DASHBOARD_OVERVIEW_MINUTE_DATA(
    ID 			VARCHAR2(25),
    owner 		VARCHAR2(128) NOT NULL,
    ownerParent VARCHAR2(128) NOT NULL,
    records 	NUMBER(8) NOT NULL,
    rangeMarker TIMESTAMP NOT NULL,
    tag 		VARCHAR2(10),
    rangeStart 	TIMESTAMP NOT NULL,
    rangeEnd 	TIMESTAMP NOT NULL,
    state 	    NUMBER(1) NOT NULL,
    threadID 	VARCHAR2(150) NOT NULL,
    sign 	    VARCHAR2(150) NOT NULL
) tablespace ENCCIMSDATA01;

ALTER TABLE DASHBOARD_OVERVIEW_MINUTE_DATA ADD CONSTRAINT "PK_MINUTE_DATA" PRIMARY KEY ("ID");

ALTER TABLE DASHBOARD_OVERVIEW_MINUTE_DATA ADD CONSTRAINT
CONSTRAINT_DASHBOARD_OVERVIEW_MINUTE_DATA_SIGN UNIQUE (SIGN);

grant select, insert, update, delete on DASHBOARD_OVERVIEW_MINUTE_DATA to CIMS_DASHBOARD_RW_ROLE;
grant select, insert, update, delete on DASHBOARD_OVERVIEW_MINUTE_DATA  to CIMS_DASHBOARD_RO_SUP_ROLE;

-- //@UNDO
DROP TABLE DASHBOARD_OVERVIEW_MINUTE_DATA;