name: ftp tool
on:
  workflow_call:
    inputs:
      server:
        required: true
        type: string
      type:
        required: true
        type: string
      user:
        type: string
      password:
        type: string
        required: true
      remotDir:
        type: string
        required: true
      stepName:
        type: string
        required: true
runs:
  using: "composite"
  steps:
    - name: set ftp tool
      shell: bash
      run: |
        if ! command -v ftp &> /dev/null; then
            echo "FTP is not installed. Installing..."
            sudo apt update
            sudo apt install -y ftp
        else
            echo "FTP is already installed."
        fi
    - name: tar fils
      shell: bash
      if: ${{ inputs.type == 'UPLOAD' }}
      run: |
        #压缩文件夹下所有文件
        tar -czvf ${{inputs.stepName}}.tar.gz ./file
        ls
    - name: ftp upload
      shell: bash
      if: ${{ inputs.type == 'UPLOAD' }}
      run: |
        ftp -n ${{inputs.server}} <<EOF
        user ${{inputs.user}} ${{inputs.password}}
        mkdir ${{inputs.remotDir}}
        put ${{inputs.stepName}}.tar.gz ${{inputs.remotDir}}/${{inputs.stepName}}.tar.gz
        EOF
    - name: ftp download
      shell: bash
      if: ${{ inputs.type == 'DOWNLOAD' }}
      run: |
        ftp -n ${{inputs.server}} <<EOF
        user ${{inputs.user}} ${{inputs.password}}
        get ${{inputs.remotDir}}/${{inputs.stepName}}.tar.gz ${{inputs.stepName}}.tar.gz
        EOF
        tar -vxf ${{inputs.stepName}}.tar.gz
    - name: ftp delete
      shell: bash
      if: ${{ inputs.type == 'DELETE' }}
      run: |
        ftp -n ${{inputs.server}} <<EOF
        user ${{inputs.user}} ${{inputs.password}}
        cd ${{inputs.remotDir}}
        mdelete *
        cd ..
        rmdir ${{inputs.remotDir}}
        EOF
        
