name: Run MySQL script
on:
 push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up MySQL
      uses: mysql/setup-mysql@v2
      with:
        mysql-version: '8.0'
        mysql-host: 175.27.254.42
        mysql-port: 3306
        mysql-user: root
        mysql-password: 'Ppe7LDR6FBWpL4Me'
    - name: Run MySQL script
      run: 
        ls
        cd sql
        echo "START TRANSACTION;" > new_test.sql
        cat test.sql >> new_test.sql
        echo "COMMIT;" >> new_test.sql
        cat new_test.sql
        # 运行 SQL 脚本或执行 MySQL 命令a
        mysql -h 175.27.254.42 -P 3306 -u root -pPpe7LDR6FBWpL4Me -D fc < new_test.sql
