name: dml pgsql sql

on:
  workflow_dispatch:

jobs:
  exeSql:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run SQL script
      run: |
        ls
        # 安装 mysql-client
        sudo apt-get update
        sudo apt-get install -y postgresql-client
        psql --version
        cd sql
        echo "BEGIN;" > new_test.sql
        cat test.sql >> new_test.sql
        echo "COMMIT;" >> new_test.sql
        cat new_test.sql
        
        # 运行 SQL 脚本或执行 MySQL 命令
        PGPASSWORD=password psql -h 117.88.100.240 -p 15433 -d postgres -U postgres -f new_test.sql
