name: Download Code

on:
  push:
    branches:
      - main

jobs:
  download_code:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: 11.0.1
        distribution: 'adopt'
    - name: Run database migrations
      run: |
        chmod +x mybatis-migrations-3.3.9/bin/migrate
        cd mybatis-migrations-3.3.9
        ./bin/migrate status --env=development2
        ./bin/migrate -script 20231220091623_create_users_table2.sql down --env=development2
        ./bin/migrate status --env=development2
