name: test actifact

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: clean
      run: |
        json=$(curl -L \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GIT_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/xudongk/testMybatis/actions/artifacts)
        sudo apt-get update
        sudo apt-get install jq
        artifact_id=$(echo "$json" | jq '.artifacts[] | select(.name == "artifact") | .id')
        curl -L \
          -X DELETE \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer  ${{ secrets.GIT_TOKEN }}"\
          -H "X-GitHub-Api-Version: 2022-11-28" \
         https://api.github.com/repos/xudongk/testMybatis/actions/artifacts/$artifact_id
    - name: Checkout code
      uses: actions/checkout@v2
    - name: upload file
      uses: actions/upload-artifact@v2
      with:
        name: artifact
        path: ./*
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: down file
      uses: actions/download-artifact@v2
      with:
        name: artifact
  
    - name: check file
      run: |
        ls
    
