name: dml sql

on:
  workflow_dispatch:

jobs:
  exeSql:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run SQL script
      run: |
        ls
        # 安装 mysql-client
        sudo apt-get update
        sudo apt-get install mysql-client -y
        cd sql
        mysql -h 175.27.254.42 -P 3306 -u root -pPpe7LDR6FBWpL4Me -D fc -e "SET autocommit = 0;"
        for file in $(ls -r *.sql | sort -t_ -k1,1nr); do
          mysql -h 175.27.254.42 -P 3306 -u root -pPpe7LDR6FBWpL4Me -D fc < '$file' || exit 1
        done
        mysql -h 175.27.254.42 -P 3306 -u root -pPpe7LDR6FBWpL4Me -D fc -e "COMMIT;"
        mysql -h 175.27.254.42 -P 3306 -u root -pPpe7LDR6FBWpL4Me -D fc -e "SET autocommit = 1;"
        # # echo "START TRANSACTION;" > new_test.sql
        # # ls *.sql | sort -t_ -k1,1n | xargs cat > new_test.sql
        # echo "START TRANSACTION;" | cat - $(ls *.sql | sort -t_ -k1,1n) > new_test.sql
        # echo "COMMIT;" >> new_test.sql
        # cat new_test.sql
        
        # 运行 SQL 脚本或执行 MySQL 命令
        # mysql -h 175.27.254.42 -P 3306 -u root -pPpe7LDR6FBWpL4Me -D fc < new_test.sql
