name: dml sql

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: upload file
      uses: actions/upload-artifact@v2
      with:
        name: artifact
        path: ./*
  test:
    runs-on: ubuntu-latest
    steps:
    - name: check file
      run: |
        ls
    
