name: Download Code

on:
  push:
    branches:
      - main

jobs:
  download_code:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run database migrations
      run: |
        ls
