name: test actifact

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: upload file
      uses: actions/upload-artifact@v2
      with:
        name: artifact
        path: ./*
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    # - name: down file
    #   uses: actions/download-artifact@v2
    #   with:
    #     name: artifact
    - name: Delete artifact
      run: |
        response=$(curl -s https://api.github.com/repos/xudongk/testMybatis/actions/runs/${{ github.run_id }}/artifacts)
        echo $response
        artifact_id=$(echo $response | awk -F'"id":' '{sub(/^ */, "", $2); print $2}' | awk -F',' '{print $1}')
        echo $artifact_id
        curl -L \
        -X DELETE \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer ${{ secrets.GIT_TOKEN }}" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        https://api.github.com/repos/xudongk/testMybatis/actions/artifacts/$artifact_id
    # - name: check file
    #   run: |
    #     ls
    
