name: Download Code

on:
  push:
    branches:
      - main

jobs:
  download_code:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: 1.11
    - name: Run database migrations
      run: |
        cd mybatis-migrations-3.3.9/bin
        migrate -cp lib/mysql-connector-java-8.0.19.jar -c ./sit.properties up
