name: Download Code

on:
  push:
    branches:
      - main

jobs:
  download_code:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run database migrations
      run: |
        cd mybatis-migrations-3.3.9/bin
        migrate -cp lib/ojdbc.jar -c ./database.properties up
