
name: Download Code

on:
  push:
    branches:
      - main

jobs:
  download_code:
    runs-on: ubuntu-latest

    steps:
    - name: step1
      run: |
       echo 111
    - name: step2
      run: |
        echo 222
      if: ${{ failure() }}
    - name: step3
      run: |
       echo 333
