name: dml sql

on:
  workflow_dispatch:

jobs:
  exeSql:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run SQL script
      run: |
        ls
        # 安装 mysql-client
        sudo apt-get update
        sudo apt-get install mysql-client -y
        echo "START TRANSACTION;" > new_test.sql
        for file in $(ls -r sql/*.sql | sort -t_ -k1,1n); do
        	echo "SOURCE $file;" >> new_test.sql
        done
        echo "COMMIT;" >> new_test.sql
        mysql -h 175.27.254.42 -P 3306 -u root -pPpe7LDR6FBWpL4Me -D fc < new_test.sql

        # cd sql
        # MYSQL_HOST="175.27.254.42"   # MySQL服务器地址
        # MYSQL_USER="root"        # MySQL登录用户名
        # MYSQL_PASSWORD="Ppe7LDR6FBWpL4Me"       # MySQL登录密码（如果有）
        # DATABASE="fc"    # 要操作的数据库名称
        # # 连接到MySQL服务器
        # mysql -h $MYSQL_HOST -u $MYSQL_USER -p$MYSQL_PASSWORD $DATABASE << EOF
        # # SQL文件列表
        # USE $DATABASE;
        # BEGIN TRANSACTION;
        
        # -- 构建动态SQL
        # SET @sql = 'BEGIN TRANSACTION; ' +
        #            'SOURCE 01_test.sql; ' +
        #            'SOURCE 02_testPg.sql; ' +
        #            'COMMIT;';
        # -- 执行动态SQL
        # EXEC sp_executesql @sql;
        # mysql -h 175.27.254.42 -P 3306 -u root -pPpe7LDR6FBWpL4Me -D fc -e "START TRANSACTION;"
        # sql_files=$(ls -r *.sql | sort -t_ -k1,1nr)
        # 遍历并执行每个 SQL 文件
        # for file in $sql_files; do
        #     echo "执行文件: $file"
        #     mysql -h 175.27.254.42 -P 3306 -u root -pPpe7LDR6FBWpL4Me -D fc < "$file"
        #     # 检查 SQL 文件的执行结果
        #     if [ $? -ne 0 ]; then
        #         echo "文件执行失败: $file"
        #         # 执行失败，回滚事务
        #         mysql -h 175.27.254.42 -P 3306 -u root -pPpe7LDR6FBWpL4Me -D fc -e "ROLLBACK;"
        #         exit 1
        #     fi
        # done
        # mysql -h 175.27.254.42 -P 3306 -u root -pPpe7LDR6FBWpL4Me -D fc -e "COMMIT;"
        
        # for file in $(ls -r *.sql | sort -t_ -k1,1nr); do
        #   mysql -h 175.27.254.42 -P 3306 -u root -pPpe7LDR6FBWpL4Me  -D fc -e "CALL execute_sql_file('$file','$database_name');" > output.txt
        #   cat output.txt
        # done
        
        # # echo "START TRANSACTION;" > new_test.sql
        # # ls *.sql | sort -t_ -k1,1n | xargs cat > new_test.sql
        # echo "START TRANSACTION;" | cat - $(ls *.sql | sort -t_ -k1,1n) > new_test.sql
        # echo "COMMIT;" >> new_test.sql
        # cat new_test.sql
        
        # 运行 SQL 脚本或执行 MySQL 命令
        # mysql -h 175.27.254.42 -P 3306 -u root -pPpe7LDR6FBWpL4Me -D fc < new_test.sql
