name: Test env

on:
  workflow_dispatch:
    inputs:
      appName:
        type: string
    secrets:
      CMS_MYSQL_DRIVER:
        required: true
      CMS_MYSQL_PASSWORD:
        required: true
      CMS_MYSQL_URL:
        required: true
      CMS_MYSQL_USERNAME:
        required: true

jobs:
  download_code:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run database migrations
      run: |
        echo "${{ secrets.CMS_MYSQL_DRIVER }}"
        echo "${{ secrets.CMS_MYSQL_PASSWORD }}"
        echo "${{ secrets.CMS_MYSQL_URL }}"
        echo "${{ secrets.CMS_MYSQL_USERNAME }}"
        cd mybatis-migrations-3.3.9/environments
        ls
        cat development2.properties
        if [ "${{ inputs.appName }}" == "CMS" ];then
          sed -i 's,driver,driver="${{ secrets.CMS_MYSQL_DRIVER }}",g' development2.properties
          sed -i 's,url,url="${{ secrets.CMS_MYSQL_URL }}",g' development2.properties
          sed -i 's,username,username="${{ secrets.CMS_MYSQL_USERNAME }}",g' development2.properties
          sed -i 's,password,password="${{ secrets.CMS_MYSQL_USERNAME }}",g' development2.properties
        fi
        cat development2.properties
