name: Download Code

on:
  push:
    branches:
      - main

jobs:
  download_code:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: 11.0.1
        distribution: 'adopt'
    - name: Run database migrations
      run: |
        cd mybatis-migrations-3.3.9/bin
        chmod +x migrate
        ./migrate up
